Proyecto_Codisan/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users
  resources :courses
  
  namespace :admin do
    resources :matters
    resources :observers do 
      resources :fault_observers, module: :observers do
      end
    end
    resources :information
    resources :photos
    resources :faults
    resources :courses  do
      resources :matters, module: :courses do
        resources :tasks, module: :matters do  
        end
        resources :notes,  module: :matters do
        end 
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "dashboard#index"
end

Proyecto_Codisan/app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

Proyecto_Codisan/app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_photo, only: [:show, :edit, :destroy, :update]

  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "foto creada correctamente"
      redirect_to admin_photos_path
    else
      flash[:alert] = "Error al guardar la foto"
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    if @photo.update(photo_params)
      flash[:success] = "foto actualizada correctamente"
      redirect_to admin_photos_path
    else
      flash[:alert] = "Error al actualizar la foto"
      render :edit
    end
  end

  def destroy
    if @photo.destroy
      flash[:success] = "foto eliminada"  
      redirect_to admin_photos_path
    else
      flash[:alert] = "Error al eliminar la foto"
    end
  end

  private

   def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:name_photo, :description, :avatar)
  end
end

Proyecto_Codisan/app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    if @photo.save
      flash[:success] = "foto creada correctamente"
      redirect_to photos_path
    else
      flash[:alert] = "Error al guardar la foto"
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def update
    if @photo.update(photo_params)
      flash[:success] = "foto actualizada correctamente"
      redirect_to photos_path
    else
      flash[:alert] = "Error al actualizar la foto"
      render :edit
    end
  end

  def destroy
    if @photo.destroy
      flash[:success] = "foto eliminada"  
      redirect_to photos_path
    else
      flash[:alert] = "Error al eliminar la foto"
    end
  end

  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

  def photo_params
    params.require(:photo).permit(:name_photo, :description, :avatar)
  end

end

Proyecto_Codisan/app/helpers/photos_helper.rb
module PhotosHelper
end

Proyecto_Codisan/app/views/admin/photos/_form-photos.html.erb
<div class="container-fluid">
  <%= button_to "Volver", admin_photos_path, method: :get, class:"btn btn-primary", id:"btn-back" %>
  <div class="row">
    <div class="col-8" id="form-imagen">
      <%= simple_form_for [:admin, @photo ] do |f| %>
        <h5>
          <%= f.label :name_photo, "Nombre de la imagen:" %>
        </h5>
        <%= f.text_field :name_photo %>
          <br><br>
        <h5>Descripcion de la imagen:</h5>
        <%= f.text_area(:description, size: '71x10', id: 'text-area')%>
        <%= f.file_field :avatar %>
        <br><br>
          <%= f.submit "Guardar", class:"btn btn-primary", id:"botonesFotos" , onclick: "return confirmDestroy('¿Desea Guardar esto?')"%>
        <% end %>
    </div>
  </div>
</div>

<script>
function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}
</script>

Proyecto_Codisan/app/views/admin/photos/edit.html.erb
<%= render 'form-photos' %>

Proyecto_Codisan/app/views/admin/photos/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= button_to "Agregar nueva foto" , new_admin_photo_path(), method: :get, class:"btn btn-primary", id:"botonesFotos" %>
      <%= button_to "atras", root_path, method: :get, class:"btn btn-primary", id:"btn-back" %>
      <table class="table" id="table">
        <thead>
          <tr>
            <th scope="col">Nombre</th>
            <th scope="col">Imagen</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @photos.each do |photo| %>
            <tr>
              <td>
                <%= photo.name_photo %>
              </td>
              <td>
                <div id="list-photo">
                  <%= image_tag photo.avatar.url, id: 'imagen-dashboard' %>
                </div>
              </td>
              <td>
                <div id="list-description">
                  <%= photo.description  %>
                </div>
              </td>
              <td>
                <%= button_to "Editar" , edit_admin_photo_path(photo), method: :get, class:"btn btn-primary", id:"botonesFotos" %>
                <%= button_to "Eliminar" , admin_photo_path(photo), onclick: "return confirmDestroy('¿Desea eliminar esto?')", method: :delete, class:"btn btn-primary", id:"botonesFotos" %>
              </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>


<script>
function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}
</script>

Proyecto_Codisan/app/views/admin/photos/new.html.erb
<%= render 'form-photos' %>