Proyecto_Codisan/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users
  resources :courses
  
  namespace :admin do
    resources :matters
    resources :observers do 
      resources :fault_observers, module: :observers do
      end
    end
    resources :information
    resources :photos
    resources :faults
    resources :courses  do
      resources :matters, module: :courses do
        resources :tasks, module: :matters do  
        end
        resources :notes,  module: :matters do
        end 
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "dashboard#index"
end

Proyecto_Codisan/app/models/observer.rb
class Observer < ApplicationRecord
    belongs_to :student, class_name: 'User'
    has_many :fault_observers
    has_many :faults, through: :fault_observers
end

Proyecto_Codisan/app/controllers/admin/observers/fault_observers_controller.rb
class Admin::Observers::FaultObserversController < ApplicationController
    before_action :authenticate_user!
    before_action :set_observer

    def new
        @fault_observer = @observer.fault_observers.new
        @faults = Fault.all
    end

    def create
        @fault_observer = @observer.fault_observers.new(fault_observer_params)
        if @fault_observer.save
          flash[:alert] = "creado correctamente"
          redirect_to new_admin_observer_fault_observer_path
        else
            flash[:alert] = "Error al crear"
            redirect_to new_admin_observer_fault_observer_path
        end
      end

      def edit
        @fault_observer = @observer.fault_observers.find(params[:id])
        @faults = Fault.all
      end

      def update
        @fault_observer = @observer.fault_observers.find(params[:id])
        if @fault_observer.update(fault_observer_params)
            
          flash[:alert] = "falta actualizada correctamente"
          redirect_to admin_observers_path
        else
          flash[:alert] = "Error al actualizar la falta"
          render :edit
        end
    end

     def destroy
        @fault_observer = @observer.fault_observers.find(params[:id])
        if  @fault_observer.destroy
            flash[:success] = "falta eliminada"  
            redirect_to admin_observers_path
        else
            flash[:alert] = "Error al eliminar la falta"
            redirect_to admin_observers_path
        end
     end

    private
        def fault_observer_params
            params.require(:fault_observer).permit(:description, :observer_id, :fault_id)
        end

        def set_observer
            @observer = Observer.find(params[:observer_id])
        end
end

Proyecto_Codisan/app/controllers/admin/observers_controller.rb
class Admin::ObserversController < ApplicationController
  before_action :authenticate_user!
  before_action :set_observer, only:[:show]

  def index
    @students = User.all
    #busqueda de estudiantes por documento
    @document = params[:document]
    if @document
      @students = User.where(:document => @document)
    else
      @students = User.all
    end

    @observadores = Observer.pluck(:id, :student_id)
  end

  def show
    @observer = Observer.find(params[:id])
    @fault_observers = @observer.fault_observers
  end

  def new
    @observer = Observer.new 
    @students = User.all
    @observadores = Observer.pluck(:id, :student_id)
  end


  def create
    @observer = Observer.new(observer_params)
    if @observer.save
      flash[:alert] = "observador creado"
      redirect_to admin_observers_path
    else
        flash[:alert] = "Error al crear el observador"
        redirect_to admin_observers_path
    end 
  end

  # def update
  #   @ = .find(params[:id])
  # end

  # def edit
  #   @ = .find(params[:id])
  # end

  # def destroy
  #    = .find(params[:id])
  # end

  private

  def set_observer
    @observer = Observer.find(params[:id])
  end
  
    def observer_params
      params.require(:observer).permit(:student_id)
    end
end

Proyecto_Codisan/app/views/admin/observers/_form.html.erb
<%= simple_form_for [:admin, @observer] do |f| %>
  <div class="col">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">N° de documento</th>
          <th scope="col">Nombres</th>
          <th scope="col">Apellidos</th>
          <th scope="col">Accion</th>
        </tr>
      </thead>
      <tbody>
     
         <% @students.each do |user| %>
            <% if user.has_role? :student %>
            <tr>
                  <% if Observer.where(student_id: user.id).exists? %>
                  <td><%= user.document %></td>
                  <td><%= user.first_name %> <%= user.second_name %></td>
                  <td><%= user.first_last_name %> <%= user.second_last_name %></td>
                  <td>
                   observador creado
                  </td>
                  <% else %>
                  <td><%= user.document %></td>
                  <td><%= user.first_name %> <%= user.second_name %></td>
                  <td><%= user.first_last_name %> <%= user.second_last_name %></td>
                  <td>
                    <%= check_box_tag "observer[student_id]", user.id %>
                  </td>
                <% end %> 
            </tr>
          <% end %> 
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="centrar_boton_form">
    <%= f.button :submit, "Crear Observacion", class:"btn btn-primary", id:"boton_Crear_Curso", onclick: "return confirmDestroy('¿Desea Guardar esto?')"%> 
  </div>
<% end %>


<script>
function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}
</script>

Proyecto_Codisan/app/views/admin/observers/index.html.erb
<div class="container_observadores">
  <%= button_to 'Volver', root_path, method: :get, class:"btn btn-primary", id:"btn-back" %>
  <div class="row_observadores">
    <div class="row_buscardor">
      <h5 id ="h5">Estudiantes</h5>
    <%= form_tag admin_observers_path, method: :get do %>
      <input name = "document", placeholder = "Documento">
      <%= submit_tag "buscar" %>
    <%end%> 
    </div>
    <div class="row_buscardor">
      <%= button_to "Crear observador",  new_admin_observer_path(), method: :get, id: "boton-crear",  class:"btn btn-primary" %>
      <%= button_to "Crear sanción",  admin_faults_path(), method: :get, id: "boton-crear",  class:"btn btn-primary" %>
     </div>
  </div>
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">N° de documento</th>
            <th scope="col">Nombres</th>
            <th scope="col">Apellidos</th>
            <th scope="col">Accion</th>
          </tr>
        </thead>
        <tbody>
          <% @students.each do |user| %> 
            <% if user.has_role? :student %>
              <tr>
                <% @observadores.each do |estudiante| %> 
                  <% if user.id == estudiante[1]%>
                    <td><%= user.document %></td>
                    <td><%= user.first_name %> <%= user.second_name %></td>
                    <td><%= user.first_last_name %> <%= user.second_last_name %></td>
                    <td>
                      <%= link_to "observador",  admin_observer_path(estudiante[0]), method: :get, id:"quitarLinea"%>
                    </td>
                  <%end%>
                <%end%>
              </tr>
            <% end %> 
          <% end %>
        </tbody>
      </table>
</div>

Proyecto_Codisan/app/views/admin/observers/new.html.erb
<div class="container_observadores">
  <%= button_to "Volver", admin_observers_url(@observer), method: :get, class: "btn btn-primary", id: "btn-back" %>
   <div class="row_buscardor">
      <h5 id = "h5">Estudiantes</h5>
      <%= form_tag admin_observers_path, method: :get do %>
        <input name = "document", placeholder = "Documento">
        <%= submit_tag "buscar" %>
      <%end%> 
    </div>
    <div class="col">
        <%= render "form" %>    
    </div>
  </div>
</div>

Proyecto_Codisan/app/views/admin/observers/show.html.erb
<div class="container_observadores">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Codigo de cagtegoria</th>
        <th scope="col">Descripcion</th>
        <th scope="col">Sancion</th>
        <th scope="col">Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @fault_observers.each do |observador| %> 
        <tr> 
              <td><%= observador.fault.category %></td>
              <td><%= observador.description %></td>
              <td><%= observador.fault.sanction %></td>
              <td> 
                <%= link_to "Editar", edit_admin_observer_fault_observer_path(@observer, observador ), method: :get, id:"quitarLinea"%>
                <%= button_to "Eliminar", admin_observer_fault_observer_path(@observer, observador ), method: :delete, id:"quitarLinea", onclick: "return confirmDestroy('¿Desea eliminar esto?')"%>
              </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= button_to "crear", new_admin_observer_fault_observer_path(@observer, @fault_observer ), method: :get, class:"btn btn-primary", id:"boton-faltas"%>
</div>



<script>
function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}
</script>