Proyecto_Codisan/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :users
  resources :courses
  
  namespace :admin do
    resources :matters
    resources :observers do 
      resources :fault_observers, module: :observers do
      end
    end
    resources :information
    resources :photos
    resources :faults
    resources :courses  do
      resources :matters, module: :courses do
        resources :tasks, module: :matters do  
        end
        resources :notes,  module: :matters do
        end 
      end
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "dashboard#index"
end

Proyecto_Codisan/app/models/information.rb
class Information < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
end

Proyecto_Codisan/app/controllers/admin/information_controller.rb
class Admin::InformationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_information, only: [:show, :edit, :destroy, :update]

  def index
    @informations = Information.all
  end

  def show
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      flash[:success] = "registrada"
      redirect_to admin_information_index_path
    else
      flash[:alert] = "error"
    end
  end

  def edit
  end

  def update
    if @information.update(information_params)
      flash[:success] = "informacion actualizda correctamente"
      redirect_to admin_information_index_path
    else
      flash[:alert] = "Error al actualizar la informacion"
      render :edit
    end
  end

  private

  def set_information
    @information = Information.find(params[:id])
  end

  def information_params
    params.require(:information).permit(:name,:direction,:city, :email, :phone, :avatar)    
  end

end

Proyecto_Codisan/app/controllers/information_controller.rb
class InformationController < ApplicationController
  before_action :authenticate_user!
  before_action :set_information, only: [:show, :edit, :destroy, :update]

  def index
    @informations = Information.all
  end

  def show
  end

  def new
    @information = Information.new
  end

  def create
    @information = Information.new(information_params)
    if @information.save
      flash[:success] = "registrada"
    else
      flash[:alert] = "error"
    end
  end

  def edit
  end

  def update
    if @information.update(information_params)
      flash[:success] = "informacion actualizda correctamente"
      redirect_to information_index_path
    else
      flash[:alert] = "Error al actualizar la informacion"
      render :edit
    end
  end

  private

  def set_information
    @information = Information.find(params[:id])
  end

  def information_params
    params.require(:information).permit(:name,:direction,:city, :email, :phone, :avatar)    
  end

end

Proyecto_Codisan/app/helpers/information_helper.rb
module InformationHelper
end

Proyecto_Codisan/app/views/information/_form_information.html.erb
<%= simple_form_for @information do |f| %>
  <div id="form-information">
    <%= f.file_field :avatar%> 
  </div>

  <div id="form-information">
    <%= f.label :name, "Nombre de la Institucion:" %> 
    <%= f.text_field :name %>
  </div>

  <div id="form-information">
    <%= f.label :direction, "Dirección:"%> 
    <%= f.text_field :direction %>
  </div>

  <div id="form-information">
    <%= f.label :city, "Ciudad:"%> 
    <%= f.text_field :city %>
  </div>

  <div id="form-information">
    <%= f.label :email, "Correo electronico:" %> 
    <%= f.text_field :email%>
  </div>

  <div id="form-information">
    <%= f.label :phone, "Celular:"%> 
    <%= f.text_field :phone %>
  </div>
  <%=f.submit "Guardar", disable_with: 'Espere...' , id:"btn-guardar", class:"btn btn-primary", onclick: "return confirmDestroy('¿Desea guardar esto?')"%> 
<% end %>

<script>
function confirmDestroy(message) {
  if (!confirm(message)) {
    return false;
  }
}
</script>

Proyecto_Codisan/app/views/information/edit.html.erb
<%= button_to "Volver", information_index_path, method: :get , id:"btn-back-2" , class:"btn btn-primary"%>
<div class="container-fluid", id="container-information">
  <div id="id-informacion">
    <%= render 'form_information' %>  
  </div>
</div>

Proyecto_Codisan/app/views/information/index.html.erb
<div class="container-fluid" id ="list-container">
<%= link_to "Volver" , root_path, method: :get , class:"btn btn-primary", id:"btn-back" %>
  <div class="row">
    <div class="col" id ="lista">
      <ul class="list-group" id="list-info">
        <% @informations.each do |info| %>
        <div><%= image_tag info.avatar.url, id:"image"%></div>
        <div id="centrar_index_info">
          <li class="list-group-item"> <%= info.name %></li>
          <li class="list-group-item"><%= info.direction %></li>
          <li class="list-group-item"><%= info.city %></li>
          <li class="list-group-item"> <%= info.email %></li>
          <li class="list-group-item"><%= info.phone %></li>
        </div>
              <%= button_to "Editar informacion", edit_information_path(@informations.ids), method: :get,class:"btn btn-primary", id:"btn-back" %>
        <% end %>
        <div id="btn1">
        </div>
      </ul>
    </div>
  </div>
</div>

Proyecto_Codisan/app/views/information/new.html.erb
<%= button_to "Volver", information_index_path, method: :get , id:"btn-back-2" , class:"btn btn-primary"%>
<div class="container-fluid", id="container-information">
  <div id="id-informacion">
    <%= render 'form_information' %>
  </div>
</div>